### ISSUE TITLE
Data Guide for BuzzFeed Colombia regional

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#11]
Example of CSV: https://github.com/BuzzFeedNews/zika-data/blob/master/data/parsed/colombia/colombia-2016-01-29.csv

need to have `data_field`s for:
- samples_received
- samples_testable
- samples_tested
- samples_in_progress

**Comment by majohansson** [comment]
Are these still needed? Can you update current CO_Data_Guide?

**Comment by chendaniely** [comment]
@majohansson Yes these are still needed. I have to clean the Regional reports.  I will take care of it when the regional data gets entered.
