### ISSUE TITLE
US data for the beginning of August?

### ISSUE THREAD

**Issue by malon** [cdcepi/zika#114]
I've seen I can get the 2016-08-31 data here http://www.cdc.gov/zika/geo/united-states.html
but I would like to study the evolution during August too and the repo only has the reports till July included. Is there a history in CDC where I can download the other weeks of August? or any other way I can get that?

Thank you very much for making this public!

**Comment by malon** [comment]
Well, I'll answered myself:
https://web.archive.org/web/*/http://www.cdc.gov/zika/geo/united-states.html
Still, if there is any way to access this differently could be great, I'm missing the 3rd of August. 

Thank you!

**Comment by dmrodz** [comment]
This is really helpful--thanks!

**Comment by malon** [comment]
I've found also the data for the 3rd of August, I'll upload it to the repo soon.
