### ISSUE TITLE
Fix Unknown Municipalities for Colombia

### ISSUE THREAD

**Issue by lematt1991** [cdcepi/zika#124]
It seems as though the first municipality for each department in Colombia is listed as `Unknown` in the [CO_Places.csv](https://github.com/cdcepi/zika/blob/master/Colombia/CO_Places.csv) file.  Is it possible to fix these?  If you can point me in the direction of the script that generates this file, I'd be happy to look into it and submit a pull request.

Thanks

**Comment by dmrodz** [comment]
@ml9951 CO-NIH is reporting those that way. They refer to unknown municipalities within a department that reports cases.

**Comment by lematt1991** [comment]
I see, thanks for the clarification @dmrodz.
