### ISSUE TITLE
Posible inconsistencia Zika en la provincia de Córdoba, Argentina

### ISSUE THREAD

**Issue by CristhianBoujon** [cdcepi/zika#129]
Estoy siguiendo los casos acumulados confirmados en la provincia de Córdoba y creo haber encontrado un error en los datos, como pueden ver en la imagen que adjunto. Creo que "value" para los dos casos señalados en rojo debería ser igual a 1.

![capture](https://cloud.githubusercontent.com/assets/1195235/20537309/6f66de8c-b0cb-11e6-8b35-c01295fbc4f3.PNG)

**Comment by dmrodz** [comment]
@Overflow012 Thanks for catching this. Will be reviewing/changing any inconsistencies soon & will close issue upon completion.
