### ISSUE TITLE
incomplete entry for Colombia pre-2017

### ISSUE THREAD

**Issue by TAlexPerkins** [cdcepi/zika#181]
The only data that have been entered for Colombia before 2017 pertained specifically to pregnant women. It would be really helpful to have confirmed and suspected case numbers for the population as a whole. By *department* would be a good place to start if the more numerous municipalities are slowing things down.

**Comment by dmrodz** [comment]
@TAlexPerkins 
That data can be found [here](https://github.com/cdcepi/zika/tree/master/Colombia/Municipality_Zika)
Thanks!
