### ISSUE TITLE
data available for Costa Rica

### ISSUE THREAD

**Issue by TAlexPerkins** [cdcepi/zika#182]
Data are available from Costa Rica for 2017 that would be valuable to add to the repository: https://www.ministeriodesalud.go.cr/index.php/centro-de-informacion/material-publicado/articulos?id=859

In addition, here is one bulletin from 2016, although I do not currently see any additional reports from 2016 still available (they may be there though). [costarica_20161121.pdf](https://github.com/cdcepi/zika/files/1310934/costarica_20161121.pdf)

**Comment by dmrodz** [comment]
Thanks @TAlexPerkins ,
Please, let us know if you'd be willing to contribute to add this data.

**Comment by TAlexPerkins** [comment]
Sorry, I realistically do not have time to do the data entry on this but am doing what I can to recruit others to help with this repo!
