### ISSUE TITLE
inconsistent NA values in El Salvador

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#32]
`NA`  values in [Epidemiological_Bulletin-2016-03-12.csv](https://github.com/cdcepi/zika/blob/master/El_Salvador/Epidemiological_Bulletin/data/Epidemiological_Bulletin-2016-03-12.csv) have values of `N/A` in the file.

Should be just `NA`

**Comment by majohansson** [comment]
@chendaniely @bndoone: Fixed NAs
