### ISSUE TITLE
NA values in brazil Location

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#35]
Brazil data for
- [2016-02-27](https://github.com/cdcepi/zika/blob/master/Brazil/COES_Microcephaly/data/COES_Microcephaly-2016-02-27.csv)
- [2016-03-12](https://github.com/cdcepi/zika/blob/master/Brazil/COES_Microcephaly/data/COES_Microcephaly-2016-03-12.csv)
- [2016-03-22](https://github.com/cdcepi/zika/blob/master/Brazil/COES_Microcephaly/data/COES_Microcephaly-2016-03-22.csv)

have `NA` values under the `location` but have a value for `value`, how are those rows interpreted?

**Comment by majohansson** [comment]
fixed
