### ISSUE TITLE
Haiti Admin 1 location is not the country

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#39]
the first location in the [Haiti Data](https://github.com/cdcepi/zika/blob/master/Haiti/Evolution-Epidimie-du-ZIKA/data/Evolution-Epidimie-du-ZIKA-2016-02-03.csv) should be `Haiti`.  All but one of the values have the country listed as the first loction value.

E.g., should be `Haiti-Artibonite-Desssalines_Marchand` not just `Artibonite-Desssalines_Marchand`

**Comment by majohansson** [comment]
Thanks for the fix @chendaniely
