### ISSUE TITLE
Brazil data guide 

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#5]
the csv file on github [here](https://github.com/BuzzFeedNews/zika-data/blob/master/data/parsed/brazil/brazil-microcephaly-2016-01-23-table-2.csv)

has 2 columns that are not in the current brazil data guide.

how should `microcephaly_indicative_of_infection` and `microcephaly_zika_positive` be coded?

**Comment by majohansson** [comment]
The corresponding table has not been included in the most recent reports which we started with, it appears to have been discontinued. Your names are good, but as the variables come from microcephaly_confirmed, they could alternatively be coded as:
BR0009, microcephaly_confirmed_infection_signs
BR0010, microcephaly_confirmed_zikv_positive
