### ISSUE TITLE
breakdown of sa and jb cases

### ISSUE THREAD

**Issue by YoJimboDurant** [cdcepi/zika#62]
Hi All - I noticed on http://www.cdc.gov/zika/geo/united-states.html that we are now breaking down number of pregnant, sexually acquired , Guillain-Barré syndrome cases for states and territories. Do we want to capture this information? If so, where?

**Comment by cdcepi** [comment]
Yes, please do capture that information. Make sure you have the latest version of the data guide and add new fields to capture those additional data points. Then add that data into the new csv's. It is okay that it wasn't captured previously.
