### ISSUE TITLE
United_States-Florida-Miami-Dade_County has 4 location levels instead of 3

### ISSUE THREAD

**Issue by chendaniely** [cdcepi/zika#69]
the data dictionary specifies:
`[country]-[state/province]-[county/municipality/city]`

but there is data that looks like this: `United_States-Florida-Miami-Dade_County`
which have 4 parts when split with `-`

**Comment by dmrodz** [comment]
Yes, I saw that for the FDH reports..
Maybe we can just change to:
`United_States-Florida-Miami_Dade_County`
What do you think?

**Comment by chendaniely** [comment]
that seems reasonable, the only potential problem would be figuring out the difference between
- Dade_county
- Miami
- Miami_Dade_county

But not sure how much of a concern that would be.

**Comment by dmrodz** [comment]
@chendaniely This is fixed. Changed to `United_States-Florida-Miami_Dade_County`.
There are no `Miami` or `Miami_Dade_county` by themselves for now.
Closing issue--Thanks!
